version: '3.8'
services:
  postgres:
    #image: postgres
    build: ./postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=SBaitman123!
    command:
      - "postgres"
      - "-c"
      - "shared_preload_libraries=pg_cron"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    image: postgrest/postgrest:v12.0.2
    ports:
      - "3000:3000"
    volumes:
      - ./postgrest.conf:/etc/postgrest.conf:ro
    command: ["postgrest", "/etc/postgrest.conf"]
    depends_on:
      postgres:
        condition: service_healthy
  redis:
    image: redis
    ports:
      - 6379:6379
  kafka:
    image: bitnami/kafka
    ports:
      - 9092:9092
volumes:
  postgres-data:
    driver: local