version: '3.8'
services:
  postgres:
    #image: postgres
    build: ./postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=SBaitman123!
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - 6379:6379
  kafka:
    image: apache/kafka
    ports:
      - 9092:9092
volumes:
  postgres-data:
    driver: local